CREATE DATABASE IF NOT EXISTS c6qlf215vw2607d0;

USE c6qlf215vw2607d0;

DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers (
  id INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(100) NOT NULL,
  devoured BOOLEAN NOT NULL,
  PRIMARY KEY (id));